### ISSUE TITLE
Map not working

### ISSUE THREAD

**Issue by hermann-san** [dmpop/pellicola#39]
Hi, I'm new to Pellicola and today I did install it on my Debian server. However, the map is not working. After I've clicked on the map icon, a new browser tab opens and nothing is loading.
When checking the browser inspection - network analytics , it state's 
`500 Internal Server Error  -  Referrer Policy  - strict-origin-when-cross-origin`
I assume this is because I'm running my server behind an external Proxy server and the leaflet map has a CSRF protection. However, I did access the server from inside (private IP), not through the proxy. From that I would think it's not a proxy issue.
Does someone happen to have a hint what I could check or do next?

I tried to install this at home (DSL NAT environment) and  I had a similar issue (map is not loading) when I access the map from a local (private) IP address. The error messege in the browser console is different though and I can at lease see the zoom buttons, but nothing else. 
```
Uncaught ReferenceError: NAN is not defined
<anonymous> http://192.168.178.131/pellicola/map.php:48

Error: Promised response from onMessage listener went out of scope

Uncaught Error: Set map center and zoom first.
```

**Comment by dmpop** [comment]
Yeah, the map feature is finicky. So far, I identified one issue that breaks the map: _UserComment_ EXIF field contains single or double quotes.

I've just pushed the 7181bdc70b7aade4f727fa3ed3c2bf4d61e00142 commit that hopefully fixes the issue (although I haven't tested it).

**Comment by hermann-san** [comment]
thanks for looking into this.
I've tried the fixed version, but there it's still not working. 
Maybe I didn't properly  configured the php extentions. Enlarging the image also doesn't work. It come's up with a 404 after I click the thumbnail.

I did install GD 
`apt-get install php8.2-gd`
To me it looks like exif is already installed. I simply uncommented the corresponding line in the php.ini and restarted the server.

```
extension=gd
extension=mbstring
extension=exif      ; Must be after mbstring as it depends on it
```
did I miss something?

**Comment by dmpop** [comment]
Have you specified the correct URL in the _config.php_ file (the `$base_url` variable)?

**Comment by hermann-san** [comment]
with the addition of the directory (at the end of the URL), the full size picture does now work. But the map still doesn't work.
Does it have to be https or can it also work with http?
http://192.168.178.46/pellicola

**Comment by dmpop** [comment]
If you're running Pellicola on a server on your local network, use HTTP (http://192.168.178.46/pellicola in your case).

Can you try maps with just a single photo that you know is properly geotagged?

**Comment by dmpop** [comment]
One more thing. Try to access the maps, and when it fails, run `tail -n 15 /var/log/apache2/error.log`. If there any PHP error messages, post them here.

**Comment by hermann-san** [comment]
thanks for your hints.
The single photo I had before was indeed not geotagged, but I expected to see at least the map (without a photo), even if it was not tagged. So I deleted that image and uploaded another one that is geotagged and it now works :-)  
However, if I upload an additional photo that is not geotagged, the map won't open again.
In my view, the map function should ignore those photos that are no tagged. Should it already work that way in Pellicola?
There is always the same error message in the logs
`[Tue Jul 16 19:03:58.981115 2024] [php:error] [pid 631:tid 631] [client 192.168.178.116:55932] PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /var/www/html/pellicola/map.php:54\nStack trace:\n#0 /var/www/html/pellicola/map.php(117): gps()\n#1 {main}\n  thrown in /var/www/html/pellicola/map.php on line 54, referer: http://192.168.178.46/pellicola/
`

**Comment by dmpop** [comment]
Thanks for the feedback! It makes sense now. Indeed, having even a single non-geotagged photo breaks everything at the moment. And I haven't had time to look into it. I'm going to close this issue and create a new one. Hopefully, I'll be able to fix it sooner rather than later.

**Comment by dmpop** [comment]
I fixed it in 4c18b9678b9a594c69be74942f3cccb00b044696 Hopefully it works now.

**Comment by hermann-san** [comment]
for a shot test, it works. awesome  :star_struck:   
thanks a lot.
BTW. now there is an entry for Pellicola on [alternativto.net](https://alternativeto.net/software/pellicola/about/)

**Comment by dmpop** [comment]
Thank you! I appreciate it.
